from nacl._sodium import ffi as ffi, lib as lib
from nacl.exceptions import ensure as ensure
from typing import Any

crypto_sign_BYTES: Any
crypto_sign_SEEDBYTES: Any
crypto_sign_PUBLICKEYBYTES: Any
crypto_sign_SECRETKEYBYTES: Any
crypto_sign_curve25519_BYTES: Any
crypto_sign_ed25519ph_STATEBYTES: Any

def crypto_sign_keypair(): ...
def crypto_sign_seed_keypair(seed: Any): ...
def crypto_sign(message: Any, sk: Any): ...
def crypto_sign_open(signed: Any, pk: Any): ...
def crypto_sign_ed25519_pk_to_curve25519(public_key_bytes: Any): ...
def crypto_sign_ed25519_sk_to_curve25519(secret_key_bytes: Any): ...

class crypto_sign_ed25519ph_state:
    state: Any = ...
    def __init__(self) -> None: ...

def crypto_sign_ed25519ph_update(edph: Any, pmsg: Any) -> None: ...
def crypto_sign_ed25519ph_final_create(edph: Any, sk: Any): ...
def crypto_sign_ed25519ph_final_verify(edph: Any, signature: Any, pk: Any): ...
