from nacl._sodium import ffi as ffi, lib as lib
from nacl.exceptions import ensure as ensure
from typing import Any

def sodium_memcmp(inp1: Any, inp2: Any): ...
def sodium_pad(s: Any, blocksize: Any): ...
def sodium_unpad(s: Any, blocksize: Any): ...
def sodium_increment(inp: Any): ...
def sodium_add(a: Any, b: Any): ...
