# Copyright (C) 2018 UCSC Computational Genomics Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Launch a VM. The resource group and network will be created if launching a leader.

- name: Launch Azure VM
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create a resource group
    tags:
      - leader
    # We use resource groups to identify all instances in a cluster.
    azure_rm_resourcegroup:
      name: "{{ resgrp }}"
      location: "{{ region }}"
      state: present

  - name: Create security group that allows SSH and HTTP
    tags:
      - leader
    # All instances in a security group can communicate with each other by default,
    # so we don't have to touch that. All we have to do is open port 22 for SSH.
    azure_rm_securitygroup:
      resource_group: "{{ resgrp }}"
      name: "{{ resgrp }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create a virtual network
    tags:
      - leader
    # We don't need to run the above two steps if we're adding worker nodes.
    azure_rm_virtualnetwork:
      name: "{{ resgrp }}"
      resource_group: '{{ resgrp }}'
      address_prefixes: '192.168.0.0/16'
      state: present

  - name: Create a subnet
    tags:
      - leader
    azure_rm_subnet:
      name: "{{ resgrp }}"
      virtual_network_name: "{{ resgrp }}"
      resource_group: "{{ resgrp }}"
      address_prefix: "192.168.0.0/24"
      security_group_name: "{{ resgrp }}"
      state: present

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resgrp }}"
      name: "{{ vmname }}"
      virtual_network: "{{ resgrp }}"
      subnet: "{{ resgrp }}"
      public_ip_name: "{{ vmname }}"
      security_group: "{{ resgrp }}"
      public_ip_allocation_method: Static

  - name: Create storage account
    azure_rm_storageaccount:
      account_type: 'Standard_LRS'
      resource_group: '{{ resgrp }}'
      name: '{{ storagename }}'
      state: present

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resgrp }}"
      name: "{{ vmname }}"
      vm_size: "{{ vmsize }}"
      storage_account_name: "{{ storagename }}"
      admin_username: core
      ssh_password_enabled: false
      network_interfaces: "{{ vmname }}"
      #data_disks:
      #  - lun: 0
      #    disk_size_gb: "{{ diskSize }}"
      #    managed_disk_type: Standard_LRS
      tags:
        role: "{{ role }}"
        owner: "{{ owner }}"
      image:
        offer: CoreOS
        publisher: CoreOS
        sku: Stable
        # This is close to - but not exactly - the CoreOS version used by the AWS AMI.
        version: 1235.5.0
      ssh_public_keys:
        - { path: "/home/core/.ssh/authorized_keys", key_data: "{{ lookup('file', '{{ publickeyfile }}') }}"}
      custom_data: "{{ lookup('file', cloudconfig) }}"
