from typing import Any

class RawEncoder:
    @staticmethod
    def encode(data: Any): ...
    @staticmethod
    def decode(data: Any): ...

class HexEncoder:
    @staticmethod
    def encode(data: Any): ...
    @staticmethod
    def decode(data: Any): ...

class Base16Encoder:
    @staticmethod
    def encode(data: Any): ...
    @staticmethod
    def decode(data: Any): ...

class Base32Encoder:
    @staticmethod
    def encode(data: Any): ...
    @staticmethod
    def decode(data: Any): ...

class Base64Encoder:
    @staticmethod
    def encode(data: Any): ...
    @staticmethod
    def decode(data: Any): ...

class URLSafeBase64Encoder:
    @staticmethod
    def encode(data: Any): ...
    @staticmethod
    def decode(data: Any): ...

class Encodable:
    def encode(self, encoder: Any = ...): ...
