from nacl import encoding as encoding
from nacl.utils import EncryptedMessage as EncryptedMessage, StringFixer as StringFixer, random as random
from typing import Any, Optional

class SecretBox(encoding.Encodable, StringFixer):
    KEY_SIZE: Any = ...
    NONCE_SIZE: Any = ...
    MACBYTES: Any = ...
    MESSAGEBYTES_MAX: Any = ...
    def __init__(self, key: Any, encoder: Any = ...) -> None: ...
    def __bytes__(self): ...
    def encrypt(self, plaintext: bytes, nonce: Optional[Any] = ..., encoder: Any = ...) -> bytes: ...
    def decrypt(self, ciphertext: bytes, nonce: Optional[Any] = ..., encoder: Any = ...) -> bytes: ...