from nacl import encoding as encoding
from nacl.utils import StringFixer, random
from typing import Any, Optional, SupportsBytes

class SecretBox(encoding.Encodable, StringFixer):
    KEY_SIZE: int = ...
    NONCE_SIZE: int = ...
    MACBYTES: Any = ...
    MESSAGEBYTES_MAX: Any = ...
    def __init__(self, key: bytes, encoder: Any = ...) -> None: ...
    def __bytes__(self): ...
    def encrypt(self, plaintext: bytes, nonce: Optional[bytes] = ..., encoder: Any = ...) -> bytes: ...
    def decrypt(self, ciphertext: bytes, nonce: Optional[bytes] = ..., encoder: Any = ...) -> bytes: ...