import socketserver as SocketServer

class ThreadedTCPServer(SocketServer.ThreadingMixIn, SocketServer.TCPServer): ...


class FTPStubServer:
    def __init__(self, port: int, hostname: str = 'localhost') -> None: ...
    def files(self, name: str) -> str | None: ...
    def add_file(self, name: str, content: str) -> None: ...
    server: ThreadedTCPServer
    def run(self, timeout: int = 2) -> None: ...
    def stop(self) -> None: ...
