from .listener import Listener as Listener
from .topicobj import Topic as Topic
from typing import List, Mapping

class INotificationHandler:
    def notifySubscribe(self, pubListener: Listener, topicObj: Topic, newSub: bool): ...
    def notifyUnsubscribe(self, pubListener: Listener, topicObj: Topic): ...
    def notifyDeadListener(self, pubListener: Listener, topicObj: Topic): ...
    def notifySend(self, stage: str, topicObj: Topic, pubListener: Listener = ...): ...
    def notifyNewTopic(self, topicObj: Topic, description: str, required: List[str], argsDocs: Mapping[str, str]): ...
    def notifyDelTopic(self, topicName: str): ...

class NotificationMgr:
    def __init__(self, notificationHandler: INotificationHandler = ...) -> None: ...
    def addHandler(self, handler: INotificationHandler): ...
    def getHandlers(self) -> List[INotificationHandler]: ...
    def clearHandlers(self) -> None: ...
    def notifySubscribe(self, *args, **kwargs) -> None: ...
    def notifyUnsubscribe(self, *args, **kwargs) -> None: ...
    def notifySend(self, *args, **kwargs) -> None: ...
    def notifyNewTopic(self, *args, **kwargs) -> None: ...
    def notifyDelTopic(self, *args, **kwargs) -> None: ...
    def notifyDeadListener(self, *args, **kwargs) -> None: ...
    def getFlagStates(self) -> Mapping[str, bool]: ...
    def setFlagStates(self, subscribe: bool = ..., unsubscribe: bool = ..., deadListener: bool = ..., sendMessage: bool = ..., newTopic: bool = ..., delTopic: bool = ..., all: bool = ...): ...
